[package]
authors = ["Marc Brinkmann <git@marcbrinkmann.de>"]
name = "ulog"
version = "0.1.0"
license = "MIT"
repository = "https://github.com/mbr/ulog-rs"
documentation = "https://docs.rs/ulog-rs"
readme = "README.md"

[dependencies]
log = "0.3"
thread_local = "0.3"
